### ISSUE TITLE
Where to find the c++17 compiler? (I am not a dev)

### ISSUE THREAD

**Issue by zilexa** [enigmata/lndir#1]
Hi, I am not a developer but do need lndir for a single usecase (I would like to "backup" files synced by Syncthing by creating hardlinks immediately after syncthing API reports a file has been created)..

On Ubuntu 20.10, I get the error:
```
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

I understand I need a C++ compiler with filesystem support. I Googled and it turns out lots of developers have this issue. 
I am not a developer, could you please point me to the file or repository I need to download and install? I will only use it once to compile for Ubuntu (20.10) and never again, as I will save that executable forever!

**Comment by enigmata** [comment]
Hey, @zilexa !

There is, in effect, a guide on how to build `lndir` in the `.travis.yml` file in the root of the source tree. 

Basically, the process is as follows:

```bash
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install g++-8
cd <root of source tree>
mkdir build; cd build
export PATH=$PATH:$PWD
export CXX=g++-8
cmake ..
make
make test
ls -al lndir
```

**Comment by enigmata** [comment]
@zilexa Are you good now? Can we close this issue?

**Comment by zilexa** [comment]
Yes thanks!
